/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* ISR_AFE0 */
#define ISR_AFE0__INTC_CORTEXM4_ASSIGNED 1
#define ISR_AFE0__INTC_CORTEXM4_PRIORITY 7u
#define ISR_AFE0__INTC_NUMBER 122u
#define ISR_AFE0_INTC_CORTEXM4_ASSIGNED 1
#define ISR_AFE0_INTC_CORTEXM4_PRIORITY 7u
#define ISR_AFE0_INTC_NUMBER 122u

/* ISR_AFE1 */
#define ISR_AFE1__INTC_CORTEXM4_ASSIGNED 1
#define ISR_AFE1__INTC_CORTEXM4_PRIORITY 7u
#define ISR_AFE1__INTC_NUMBER 123u
#define ISR_AFE1_INTC_CORTEXM4_ASSIGNED 1
#define ISR_AFE1_INTC_CORTEXM4_PRIORITY 7u
#define ISR_AFE1_INTC_NUMBER 123u

/* RTC_RTC_IRQ */
#define RTC_RTC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define RTC_RTC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define RTC_RTC_IRQ__INTC_NUMBER 21u
#define RTC_RTC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define RTC_RTC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define RTC_RTC_IRQ_INTC_NUMBER 21u

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* BLE_bless_isr */
#define BLE_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr__INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr__INTC_CORTEXM0P_PRIORITY 3u
#define BLE_bless_isr__INTC_NUMBER 24u
#define BLE_bless_isr_INTC_CORTEXM0P_ASSIGNED 1
#define BLE_bless_isr_INTC_CORTEXM0P_MUX 3u
#define BLE_bless_isr_INTC_CORTEXM0P_PRIORITY 3u
#define BLE_bless_isr_INTC_NUMBER 24u

/* I2C_1_SCB_IRQ */
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ__INTC_NUMBER 42u
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_1_SCB_IRQ_INTC_NUMBER 42u

/* I2C_2_SCB_IRQ */
#define I2C_2_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_2_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_2_SCB_IRQ__INTC_NUMBER 43u
#define I2C_2_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_2_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_2_SCB_IRQ_INTC_NUMBER 43u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
